# Generated by Django 4.2.22 on 2025-06-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="excerpt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="books",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
