# Generated by Django 4.2.22 on 2025-06-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-created_on'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
