# Generated by Django 4.2.22 on 2025-06-19 16:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_options_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
